version: "3"
services:
  api:
    hostname: api
    build: ./api/
    ports:
      - 80:8080
    # volumes:
    # #   - ./api/:/app/
    # healthcheck:
    #   test: ["CMD", "curl", "api:", "ping"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 5
    networks:
      - api_net
    
networks:
  api_net:
    driver: bridge